files_from_student = [ "main.c", "maze.c", "maze.h" ]
files_from_solution = []
executable = "hw18"

[requirements-txt] # OPTIONAL: if using default file, no need to include this line or the line below

[tests]
description = """
Python test files within the tests/ directory. TAs can inject these 
files or give parameters in this toml to automatically generate them.
"""
input_directory = "inputs" # OPTIONAL, defaults to "inputs"
expected_directory = "expected" # OPTIONAL, defaults to "expected"

[tests.test_files] # OPTIONAL
weight = 10

[tests.test_compile] # OPTIONAL
weight = 10

[tests.test_memory]
weight = 20

[tests.test_memory.maze1]
command_arguments = [ "inputs/maze1" ] # this is only the arguments after the executable

[tests.test_program]
weight = 60 # splits this weight between the number of tests

[tests.test_program.maze1]
command_arguments = [ "inputs/maze1" ]
output = "stdout"
expected_output = "expected/expected1"

[tests.test_program.maze2]
command_arguments = [ "inputs/maze2" ]
output = "stdout"
expected_output = "expected/expected2"

